# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
category: Other
description: yukikaze-core is a new Haskeleton package.
ghc-options: -Wall
github: xtendo-org/yukikaze-core
license: AGPL
maintainer: XT
name: yukikaze-core
synopsis: A new Haskeleton package.
version: '0.0.0'

extra-source-files:
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

default-extensions:
- LambdaCase
- OverloadedStrings
- RecordWildCards

library:
  dependencies:
  - attoparsec
  - bytestring
  - text

  - base
  source-dirs: library

executables:
  yukikaze-core:
    dependencies:
    - base
    - yukikaze-core
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable

tests:
  yukikaze-core-test-suite:
    dependencies:
    - base
    - yukikaze-core
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite

benchmarks:
  yukikaze-core-benchmarks:
    dependencies:
    - base
    - yukikaze-core
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
